// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/user-service/user.proto

package user_service

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a new user
type CreateUserRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Email     string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password  string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role      string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	// Optional fields don't need 'default', just 'example' is helpful
	Phone         string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Age           int32  `protobuf:"varint,8,opt,name=age,proto3" json:"age,omitempty"`
	ProfilePic    string `protobuf:"bytes,9,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_user_service_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserRequest) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

// Request to get a user by ID
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_user_service_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to update a user
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID comes from the path, other fields are optional in the body
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Use 'optional' keyword for fields that might not be sent
	FirstName *string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName  *string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Password  *string `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// Can add other updatable fields here (phone, address, etc.) marked as optional
	Phone         *string `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Address       *string `protobuf:"bytes,6,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Age           *int32  `protobuf:"varint,7,opt,name=age,proto3,oneof" json:"age,omitempty"`
	ProfilePic    *string `protobuf:"bytes,8,opt,name=profile_pic,json=profilePic,proto3,oneof" json:"profile_pic,omitempty"`
	Role          *string `protobuf:"bytes,9,opt,name=role,proto3,oneof" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_user_service_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateUserRequest) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UpdateUserRequest) GetProfilePic() string {
	if x != nil && x.ProfilePic != nil {
		return *x.ProfilePic
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

// Request to delete a user
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_user_service_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response for user deletion
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_user_service_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request to list users with pagination
type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Using offset/limit is common for pagination
	Offset        int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_user_service_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response containing a list of users
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserResponse        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_user_service_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersResponse) GetUsers() []*UserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Request for user login
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_user_service_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Response for successful login
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	User          *UserResponse          `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_user_service_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *LoginResponse) GetUser() *UserResponse {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to find user by email
type FindByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEmailRequest) Reset() {
	*x = FindByEmailRequest{}
	mi := &file_proto_user_service_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEmailRequest) ProtoMessage() {}

func (x *FindByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEmailRequest.ProtoReflect.Descriptor instead.
func (*FindByEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{9}
}

func (x *FindByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Response containing user information (used by multiple RPCs)
type UserResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email     string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role      string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Use google.protobuf.Timestamp for nullable time fields if needed, and handle zero value for int64
	DeletedAt *int64 `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	// Adding username field example
	Username    string `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	IsActive    bool   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastLoginAt int64  `protobuf:"varint,11,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	// Added phone/address to response for completeness
	Phone         string `protobuf:"bytes,12,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	Age           int32  `protobuf:"varint,14,opt,name=age,proto3" json:"age,omitempty"`
	ProfilePic    string `protobuf:"bytes,15,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_user_service_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserResponse) GetDeletedAt() int64 {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return 0
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserResponse) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

func (x *UserResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserResponse) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

var File_proto_user_service_user_proto protoreflect.FileDescriptor

const file_proto_user_service_user_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/user-service/user.proto\x12\x04user\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\"\x90\b\n" +
	"\x11CreateUserRequest\x12g\n" +
	"\x05email\x18\x01 \x01(\tBQ\x92AN2,User's unique email address. Used for login.J\x16\"john.doe@example.com\"\xa2\x02\x05emailR\x05email\x12s\n" +
	"\bpassword\x18\x02 \x01(\tBW\x92AT23User's password (minimum 8 characters recommended).J\x0f\"SecureP@ss123\"\x80\x01\b\xa2\x02\bpasswordR\bpassword\x12>\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tB\x1f\x92A\x1c2\x12User's first name.J\x06\"John\"R\tfirstName\x12:\n" +
	"\tlast_name\x18\x04 \x01(\tB\x1d\x92A\x1a2\x11User's last name.J\x05\"Doe\"R\blastName\x12{\n" +
	"\x04role\x18\x05 \x01(\tBg\x92Ad22User's role within the system (e.g., user, admin).:\x04userJ\x06\"user\"\xf2\x02\t\"manager\"\xf2\x02\a\"admin\"\xf2\x02\t\"officer\"R\x04role\x12z\n" +
	"\x05phone\x18\x06 \x01(\tBd\x92Aa2;User's phone number, preferably in E.164 format (optional).J\x0e\"+14155552671\"\x8a\x01\x11^\\+[1-9]\\d{1,14}$R\x05phone\x12t\n" +
	"\aaddress\x18\a \x01(\tBZ\x92AW2\x1fUser's full address (optional).J4\"1600 Amphitheatre Parkway, Mountain View, CA 94043\"R\aaddress\x129\n" +
	"\x03age\x18\b \x01(\x05B'\x92A$2\x16User's age (optional).J\x0230\xa2\x02\x05int32R\x03age\x12\x81\x01\n" +
	"\vprofile_pic\x18\t \x01(\tB`\x92A]2)URL to user's profile picture (optional).J*\"https://example.com/profiles/johndoe.jpg\"\xa2\x02\x03urlR\n" +
	"profilePic:s\x92Ap\n" +
	"n*\x13Create User Payload2+Data required to create a new user account.\xd2\x01\x05email\xd2\x01\bpassword\xd2\x01\n" +
	"first_name\xd2\x01\tlast_name\"\xa3\x01\n" +
	"\x0eGetUserRequest\x12\x84\x01\n" +
	"\x02id\x18\x01 \x01(\tBt\x92Aq2@The unique identifier (UUID or similar) of the user to retrieve.J&\"a1b2c3d4-e5f6-7890-1234-567890abcdef\"\xa2\x02\x04uuidR\x02id:\n" +
	"\x92A\a\n" +
	"\x05\xd2\x01\x02id\"\xf8\b\n" +
	"\x11UpdateUserRequest\x12\x85\x01\n" +
	"\x02id\x18\x01 \x01(\tBu\x92Ar2AThe unique identifier of the user to update (passed in URL path).J&\"a1b2c3d4-e5f6-7890-1234-567890abcdef\"\xa2\x02\x04uuidR\x02id\x12q\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tBM\x92AJ2>Updated first name (optional). If omitted, value is unchanged.J\b\"Johnny\"H\x00R\tfirstName\x88\x01\x01\x12k\n" +
	"\tlast_name\x18\x03 \x01(\tBI\x92AF2=Updated last name (optional). If omitted, value is unchanged.J\x05\"Doe\"H\x01R\blastName\x88\x01\x01\x12\x97\x01\n" +
	"\bpassword\x18\x04 \x01(\tBv\x92As2QUpdated password (optional, min 8 characters). If omitted, password is unchanged.J\x10\"NewS3cureP@ss!\"\x80\x01\b\xa2\x02\bpasswordH\x02R\bpassword\x88\x01\x01\x12d\n" +
	"\x05phone\x18\x05 \x01(\tBI\x92AF2 Updated phone number (optional).J\x0e\"+14155552672\"\x8a\x01\x11^\\+[1-9]\\d{1,14}$H\x03R\x05phone\x88\x01\x01\x12d\n" +
	"\aaddress\x18\x06 \x01(\tBE\x92AB2\x1bUpdated address (optional).J#\"1 Loop Drive, Cupertino, CA 95014\"H\x04R\aaddress\x88\x01\x01\x12?\n" +
	"\x03age\x18\a \x01(\x05B(\x92A%2\x17Updated age (optional).J\x0231\xa2\x02\x05int32H\x05R\x03age\x88\x01\x01\x12\x8a\x01\n" +
	"\vprofile_pic\x18\b \x01(\tBd\x92Aa2*Updated URL to profile picture (optional).J-\"https://example.com/profiles/johndoe_v2.jpg\"\xa2\x02\x03urlH\x06R\n" +
	"profilePic\x88\x01\x01\x12f\n" +
	"\x04role\x18\t \x01(\tBM\x92AJ2\x1dUpdated user role (optional).J\a\"admin\"\xf2\x02\t\"manager\"\xf2\x02\a\"admin\"\xf2\x02\t\"officer\"H\aR\x04role\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\v\n" +
	"\t_passwordB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_addressB\x06\n" +
	"\x04_ageB\x0e\n" +
	"\f_profile_picB\a\n" +
	"\x05_role\"\x91\x01\n" +
	"\x11DeleteUserRequest\x12p\n" +
	"\x02id\x18\x01 \x01(\tB`\x92A]2,The unique identifier of the user to delete.J&\"a1b2c3d4-e5f6-7890-1234-567890abcdef\"\xa2\x02\x04uuidR\x02id:\n" +
	"\x92A\a\n" +
	"\x05\xd2\x01\x02id\"\xb3\x01\n" +
	"\x12DeleteUserResponse\x12O\n" +
	"\asuccess\x18\x01 \x01(\bB5\x92A22*True if the user was deleted successfully.J\x04trueR\asuccess:L\x92AI\n" +
	"G*\x15Deletion Confirmation2.Indicates whether the deletion was successful.\"\xe2\x01\n" +
	"\x10ListUsersRequest\x12m\n" +
	"\x06offset\x18\x01 \x01(\x05BU\x92AR2BNumber of items to skip before starting to collect the result set.:\x010J\x010\xa2\x02\x05int32R\x06offset\x12_\n" +
	"\x05limit\x18\x02 \x01(\x05BI\x92AF2\"Maximum number of items to return.:\x0210J\x0225Y\x00\x00\x00\x00\x00\x00Y@i\x00\x00\x00\x00\x00\x00\xf0?\xa2\x02\x05int32R\x05limit\"\xce\x03\n" +
	"\x11ListUsersResponse\x12c\n" +
	"\x05users\x18\x01 \x03(\v2\x12.user.UserResponseB9\x92A624The list of user objects found for the current page.R\x05users\x12g\n" +
	"\x05total\x18\x02 \x01(\x03BQ\x92AN2?Total number of users matching the criteria (across all pages).J\x03153\xa2\x02\x05int64R\x05total\x12M\n" +
	"\x05limit\x18\x03 \x01(\x05B7\x92A42&The limit value used for this request.J\x0225\xa2\x02\x05int32R\x05limit\x12P\n" +
	"\x06offset\x18\x04 \x01(\x05B8\x92A52'The offset value used for this request.J\x0250\xa2\x02\x05int32R\x06offset:J\x92AG\n" +
	"E*\x13Paginated User List2.A list of users along with pagination details.\"\xf2\x01\n" +
	"\fLoginRequest\x12Z\n" +
	"\x05email\x18\x01 \x01(\tBD\x92AA2\x1fUser's email address for login.J\x16\"jane.doe@example.com\"\xa2\x02\x05emailR\x05email\x12Y\n" +
	"\bpassword\x18\x02 \x01(\tB=\x92A:2\x1aUser's password for login.J\x11\"CorrectP@ssw0rd\"\xa2\x02\bpasswordR\bpassword:+\x92A(\n" +
	"&*\x11Login Credentials\xd2\x01\x05email\xd2\x01\bpassword\"\x87\x04\n" +
	"\rLoginResponse\x12\xa3\x02\n" +
	"\x05token\x18\x01 \x01(\tB\x8c\x02\x92A\x88\x022JJWT authentication token to be used for subsequent authenticated requests.J\xb3\x01\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyNDI2MjJ9.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\"\xa2\x02\x03jwtR\x05token\x12n\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03BO\x92AL26Timestamp (Unix epoch seconds) when the token expires.J\n" +
	"1678901234\xa2\x02\x05int64R\texpiresAt\x12K\n" +
	"\x04user\x18\x03 \x01(\v2\x12.user.UserResponseB#\x92A 2\x1eDetails of the logged-in user.R\x04user:\x13\x92A\x10\n" +
	"\x0e*\fLogin Result\"\x8b\x01\n" +
	"\x12FindByEmailRequest\x12f\n" +
	"\x05email\x18\x01 \x01(\tBP\x92AM2,The email address of the user to search for.J\x15\"find.me@example.com\"\xa2\x02\x05emailR\x05email:\r\x92A\n" +
	"\n" +
	"\b\xd2\x01\x05email\"\xf1\v\n" +
	"\fUserResponse\x12e\n" +
	"\x02id\x18\x01 \x01(\tBU\x92AR2\x1fUnique identifier for the user.@\x01J&\"a1b2c3d4-e5f6-7890-1234-567890abcdef\"\xa2\x02\x04uuidR\x02id\x12R\n" +
	"\x05email\x18\x02 \x01(\tB<\x92A92\x15User's email address.@\x01J\x16\"jane.doe@example.com\"\xa2\x02\x05emailR\x05email\x12@\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tB!\x92A\x1e2\x12User's first name.@\x01J\x06\"Jane\"R\tfirstName\x12<\n" +
	"\tlast_name\x18\x04 \x01(\tB\x1f\x92A\x1c2\x11User's last name.@\x01J\x05\"Doe\"R\blastName\x12@\n" +
	"\x04role\x18\x05 \x01(\tB,\x92A)2\x1aUser's role in the system.@\x01J\t\"officer\"R\x04role\x12{\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03B\\\x92AY2ATimestamp (Unix epoch seconds) when the user account was created.@\x01J\n" +
	"1678888000\xa2\x02\x05int64R\tcreatedAt\x12\x80\x01\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03Ba\x92A^2FTimestamp (Unix epoch seconds) when the user account was last updated.@\x01J\n" +
	"1678900000\xa2\x02\x05int64R\tupdatedAt\x12\x95\x01\n" +
	"\n" +
	"deleted_at\x18\b \x01(\x03Bq\x92An2VTimestamp (Unix epoch seconds) when the user was soft-deleted. Omitted if not deleted.@\x01J\n" +
	"1678901234\xa2\x02\x05int64H\x00R\tdeletedAt\x88\x01\x01\x12p\n" +
	"\busername\x18\t \x01(\tBT\x92AQ2@Unique username for the account (optional, distinct from email).@\x01J\v\"janedoe99\"R\busername\x12a\n" +
	"\tis_active\x18\n" +
	" \x01(\bBD\x92AA27Indicates whether the user account is currently active.@\x01J\x04trueR\bisActive\x12w\n" +
	"\rlast_login_at\x18\v \x01(\x03BS\x92AP28Timestamp (Unix epoch seconds) of the user's last login.@\x01J\n" +
	"1678900500\xa2\x02\x05int64R\vlastLoginAt\x12A\n" +
	"\x05phone\x18\f \x01(\tB+\x92A(2\x14User's phone number.@\x01J\x0e\"+14155552671\"R\x05phone\x12k\n" +
	"\aaddress\x18\r \x01(\tBQ\x92AN2\x14User's full address.@\x01J4\"1600 Amphitheatre Parkway, Mountain View, CA 94043\"R\aaddress\x120\n" +
	"\x03age\x18\x0e \x01(\x05B\x1e\x92A\x1b2\vUser's age.@\x01J\x0230\xa2\x02\x05int32R\x03age\x12x\n" +
	"\vprofile_pic\x18\x0f \x01(\tBW\x92AT2\x1eURL to user's profile picture.@\x01J*\"https://example.com/profiles/johndoe.jpg\"\xa2\x02\x03urlR\n" +
	"profilePic:\x13\x92A\x10\n" +
	"\x0e*\fUser DetailsB\r\n" +
	"\v_deleted_at2\xa9\x0f\n" +
	"\vUserService\x12\x92\x02\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\"\xd6\x01\x92A\xba\x01\n" +
	"\x05Users\x12\x11Create a new user\x1aVCreates a new user account. Requires email, password, first name, last name, and role.JF\n" +
	"\x03200\x12?\n" +
	"\x19User created successfully\x12\"\n" +
	" \x1a\x1e#/definitions/userUserResponse\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12\xfe\x01\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\"\xc8\x01\x92A\xaa\x01\n" +
	"\x05Users\x12\x10Get a user by ID\x1a$Retrieves a user by their unique ID.JP\n" +
	"\x03200\x12I\n" +
	"#User details retrieved successfully\x12\"\n" +
	" \x1a\x1e#/definitions/userUserResponseJ\x17\n" +
	"\x03404\x12\x10\n" +
	"\x0eUser not found\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12\x82\x02\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\"\xc6\x01\x92A\xa5\x01\n" +
	"\x05Users\x12\rUpdate a user\x1aEUpdates an existing user's details. Only provided fields are updated.JF\n" +
	"\x03200\x12?\n" +
	"\x19User updated successfully\x12\"\n" +
	" \x1a\x1e#/definitions/userUserResponse\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/users/{id}\x12\xa1\x02\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponse\"\xdf\x01\x92A\xc1\x01\n" +
	"\x05Users\x12\rDelete a user\x1a[Deletes a user by their unique ID. This might be a soft delete depending on implementation.JL\n" +
	"\x03200\x12E\n" +
	"\x19User deleted successfully\x12(\n" +
	"&\x1a$#/definitions/userDeleteUserResponse\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}\x12\x8e\x02\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\"\xcf\x01\x92A\xb6\x01\n" +
	"\x05Users\x12\n" +
	"List users\x1aIRetrieves a list of users with pagination support using offset and limit.JV\n" +
	"\x03200\x12O\n" +
	"$List of users retrieved successfully\x12'\n" +
	"%\x1a##/definitions/userListUsersResponse\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12\x9e\x02\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\"\xeb\x01\x92A\xcf\x01\n" +
	"\x0eAuthentication\x12\n" +
	"User login\x1aCAuthenticates a user and returns a JWT token upon successful login.JN\n" +
	"\x03200\x12G\n" +
	" Login successful, token returned\x12#\n" +
	"!\x1a\x1f#/definitions/userLoginResponseJ\x1c\n" +
	"\x03401\x12\x15\n" +
	"\x13Invalid credentials\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12\xa8\x02\n" +
	"\vFindByEmail\x12\x18.user.FindByEmailRequest\x1a\x12.user.UserResponse\"\xea\x01\x92A\xc3\x01\n" +
	"\x05Users\x12\x12Find user by email\x1a2Finds and retrieves a user by their email address.JD\n" +
	"\x03200\x12=\n" +
	"\x17User found successfully\x12\"\n" +
	" \x1a\x1e#/definitions/userUserResponseJ,\n" +
	"\x03404\x12%\n" +
	"#User with specified email not found\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/users/email/{email}B\xc8\x01\x92A\x8f\x01\x12e\n" +
	"\x10User Service API\x12\"API for user management operations\"(\n" +
	"\x11User Service Team\x1a\x13support@example.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ3golang-microservices-boilerplate/proto/user-serviceb\x06proto3"

var (
	file_proto_user_service_user_proto_rawDescOnce sync.Once
	file_proto_user_service_user_proto_rawDescData []byte
)

func file_proto_user_service_user_proto_rawDescGZIP() []byte {
	file_proto_user_service_user_proto_rawDescOnce.Do(func() {
		file_proto_user_service_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_service_user_proto_rawDesc), len(file_proto_user_service_user_proto_rawDesc)))
	})
	return file_proto_user_service_user_proto_rawDescData
}

var file_proto_user_service_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_user_service_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: user.CreateUserRequest
	(*GetUserRequest)(nil),     // 1: user.GetUserRequest
	(*UpdateUserRequest)(nil),  // 2: user.UpdateUserRequest
	(*DeleteUserRequest)(nil),  // 3: user.DeleteUserRequest
	(*DeleteUserResponse)(nil), // 4: user.DeleteUserResponse
	(*ListUsersRequest)(nil),   // 5: user.ListUsersRequest
	(*ListUsersResponse)(nil),  // 6: user.ListUsersResponse
	(*LoginRequest)(nil),       // 7: user.LoginRequest
	(*LoginResponse)(nil),      // 8: user.LoginResponse
	(*FindByEmailRequest)(nil), // 9: user.FindByEmailRequest
	(*UserResponse)(nil),       // 10: user.UserResponse
}
var file_proto_user_service_user_proto_depIdxs = []int32{
	10, // 0: user.ListUsersResponse.users:type_name -> user.UserResponse
	10, // 1: user.LoginResponse.user:type_name -> user.UserResponse
	0,  // 2: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	1,  // 3: user.UserService.GetUser:input_type -> user.GetUserRequest
	2,  // 4: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	3,  // 5: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	5,  // 6: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	7,  // 7: user.UserService.Login:input_type -> user.LoginRequest
	9,  // 8: user.UserService.FindByEmail:input_type -> user.FindByEmailRequest
	10, // 9: user.UserService.CreateUser:output_type -> user.UserResponse
	10, // 10: user.UserService.GetUser:output_type -> user.UserResponse
	10, // 11: user.UserService.UpdateUser:output_type -> user.UserResponse
	4,  // 12: user.UserService.DeleteUser:output_type -> user.DeleteUserResponse
	6,  // 13: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	8,  // 14: user.UserService.Login:output_type -> user.LoginResponse
	10, // 15: user.UserService.FindByEmail:output_type -> user.UserResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_user_service_user_proto_init() }
func file_proto_user_service_user_proto_init() {
	if File_proto_user_service_user_proto != nil {
		return
	}
	file_proto_user_service_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_user_service_user_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_service_user_proto_rawDesc), len(file_proto_user_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_service_user_proto_goTypes,
		DependencyIndexes: file_proto_user_service_user_proto_depIdxs,
		MessageInfos:      file_proto_user_service_user_proto_msgTypes,
	}.Build()
	File_proto_user_service_user_proto = out.File
	file_proto_user_service_user_proto_goTypes = nil
	file_proto_user_service_user_proto_depIdxs = nil
}
