# ConfigMap for API Gateway env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ride-sharing
data:
  PORT: "8081"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8081"
  SERVER_APP_NAME: "API Gateway"
  SERVER_SHUTDOWN_DELAY: "5s"
  SERVER_READ_TIMEOUT: "10s"
  SERVER_WRITE_TIMEOUT: "10s"
  SERVER_ALLOW_ORIGINS: "*"
  SERVER_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  SERVER_ALLOW_HEADERS: "Origin, Content-Type, Accept, Authorization"
  SERVER_LOGGING_ENABLED: "true"
  LOG_LEVEL: "debug"
  LOG_FORMAT: "console"
  LOG_OUTPUT: "stdout"
  APP_ENV: "development"
  DB_HOST: "ep-dry-recipe-a1xsq2aj-pooler.ap-southeast-1.aws.neon.tech"
  DB_PORT: "543"
  DB_NAME: "test"
  DB_USER: "test_owner"
  DB_PASSWORD: "npg_7wBPCKcbV6yH"
  DB_SSL_MODE: "disable"
  JWT_SECRET: "your_secret_key"
  JWT_EXPIRY: "24h"
  GRPC_HOST: "0.0.0.0"
  GRPC_PORT: "50051"
  POD_NAMESPACE: "ride-sharing-cluster" 