apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: ride-sharing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-discovery-role
  namespace: ride-sharing
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-discovery-binding
  namespace: ride-sharing
subjects:
- kind: ServiceAccount
  name: api-gateway-sa
  namespace: ride-sharing
roleRef:
  kind: Role
  name: service-discovery-role
  apiGroup: rbac.authorization.k8s.io 