// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/api-gateway/gateway.proto

package api_gateway

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "golang-microservices-boilerplate/proto/user-service"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_api_gateway_gateway_proto protoreflect.FileDescriptor

const file_proto_api_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/api-gateway/gateway.proto\x12\agateway\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1dproto/user-service/user.protoB\xf8\x02\x92A\xc0\x02\x127\n" +
	"\x11Microservices API\x12\x1dAPI Gateway for Microservices2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonR/\n" +
	"\x03401\x12(\n" +
	"&Unauthorized - Authentication requiredR-\n" +
	"\x03403\x12&\n" +
	"$Forbidden - Insufficient permissionsR\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal Server ErrorZ]\n" +
	"[\n" +
	"\n" +
	"BearerAuth\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02Z2golang-microservices-boilerplate/proto/api-gatewayb\x06proto3"

var file_proto_api_gateway_gateway_proto_goTypes = []any{}
var file_proto_api_gateway_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_gateway_gateway_proto_init() }
func file_proto_api_gateway_gateway_proto_init() {
	if File_proto_api_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_gateway_gateway_proto_rawDesc), len(file_proto_api_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_proto_api_gateway_gateway_proto_depIdxs,
	}.Build()
	File_proto_api_gateway_gateway_proto = out.File
	file_proto_api_gateway_gateway_proto_goTypes = nil
	file_proto_api_gateway_gateway_proto_depIdxs = nil
}
